defmodule Resdayn.Repo.Migrations.CreateRegions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:regions, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text)
      add(:weather, :map, null: false)
      add(:map_color, :text)
      add(:sounds, {:array, :map}, null: false, default: [])
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :disturb_sleep_creature_id,
        references(:creature_levelled_lists,
          column: :id,
          name: "regions_disturb_sleep_creature_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:regions, "regions_disturb_sleep_creature_id_fkey"))

    drop(table(:regions))
  end
end
