defmodule Resdayn.Repo.Migrations.AddContainers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:containers, primary_key: false) do
      add(
        :id,
        references(:referencable_objects,
          column: :id,
          name: "containers_id_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      add(:name, :text)
      add(:nif_model_filename, :text)
      add(:capacity, :float, null: false)
      add(:container_flags, {:array, :text}, null: false, default: [])
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "containers_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:containers, "containers_id_fkey"))

    drop(constraint(:containers, "containers_script_id_fkey"))

    drop(table(:containers))
  end
end
