defmodule Resdayn.Repo.Migrations.SimplifyInventoryItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:inventory_items, "inventory_items_npc_id_fkey"))

    drop(constraint("inventory_items", "inventory_items_pkey"))

    rename(table(:inventory_items), :npc_id, to: :holder_ref_id)

    alter table(:inventory_items) do
      remove(:item_levelled_list_id)
      remove(:miscellaneous_item_id)
      remove(:light_id)
      remove(:alchemy_apparatus_id)
      remove(:potion_id)
      remove(:ingredient_id)
      remove(:book_id)
      remove(:armor_id)
      remove(:weapon_id)
      remove(:clothing_id)
      remove(:tool_id)

      add(
        :object_ref_id,
        references(:referencable_objects,
          column: :id,
          name: "inventory_items_object_ref_id_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      modify(
        :holder_ref_id,
        references(:referencable_objects,
          column: :id,
          name: "inventory_items_holder_ref_id_fkey",
          type: :text,
          prefix: "public"
        ),
        null: false,
        primary_key: true
      )

      remove(:id)
    end
  end

  def down do
    drop(constraint("inventory_items", "inventory_items_pkey"))

    drop(constraint(:inventory_items, "inventory_items_object_ref_id_fkey"))

    drop(constraint(:inventory_items, "inventory_items_holder_ref_id_fkey"))

    alter table(:inventory_items) do
      add(:id, :bigserial, null: false, primary_key: true)

      modify(
        :npc_id,
        references(:npcs,
          column: :id,
          name: "inventory_items_npc_id_fkey",
          type: :text,
          prefix: "public"
        ),
        null: true,
        primary_key: false
      )

      remove(:object_ref_id)

      add(
        :tool_id,
        references(:tools,
          column: :id,
          name: "inventory_items_tool_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :clothing_id,
        references(:clothing,
          column: :id,
          name: "inventory_items_clothing_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :weapon_id,
        references(:weapons,
          column: :id,
          name: "inventory_items_weapon_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :armor_id,
        references(:armor,
          column: :id,
          name: "inventory_items_armor_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :book_id,
        references(:books,
          column: :id,
          name: "inventory_items_book_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :ingredient_id,
        references(:ingredients,
          column: :id,
          name: "inventory_items_ingredient_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :potion_id,
        references(:potions,
          column: :id,
          name: "inventory_items_potion_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :alchemy_apparatus_id,
        references(:alchemy_apparatus,
          column: :id,
          name: "inventory_items_alchemy_apparatus_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :light_id,
        references(:lights,
          column: :id,
          name: "inventory_items_light_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :miscellaneous_item_id,
        references(:miscellaneous_items,
          column: :id,
          name: "inventory_items_miscellaneous_item_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :item_levelled_list_id,
        references(:item_levelled_lists,
          column: :id,
          name: "inventory_items_item_levelled_list_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    rename(table(:inventory_items), :holder_ref_id, to: :npc_id)
  end
end
