defmodule Resdayn.Repo.Migrations.CreatePotions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:potions, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:nif_model_filename, :text)
      add(:icon_filename, :text)
      add(:weight, :float)
      add(:value, :bigint)
      add(:autocalc, :boolean, default: false)
      add(:effects, {:array, :map}, null: false, default: [])
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "potions_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:potions, "potions_script_id_fkey"))

    drop(table(:potions))
  end
end
