defmodule Resdayn.Repo.Migrations.CreateDialogueTopics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:dialogue_topics, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:type, :text, null: false)
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    drop(table(:dialogue_topics))
  end
end
