defmodule Resdayn.Repo.Migrations.RemoveDeferrableInitiallyFromFactionReactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:faction_reactions, "faction_reactions_target_id_fkey"))

    alter table(:faction_reactions) do
      modify(
        :target_id,
        references(:factions,
          column: :id,
          name: "faction_reactions_target_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    execute(
      "ALTER TABLE faction_reactions alter CONSTRAINT faction_reactions_target_id_fkey NOT DEFERRABLE"
    )
  end

  def down do
    drop(constraint(:faction_reactions, "faction_reactions_target_id_fkey"))

    alter table(:faction_reactions) do
      modify(
        :target_id,
        references(:factions,
          column: :id,
          name: "faction_reactions_target_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    execute(
      "ALTER TABLE faction_reactions alter CONSTRAINT faction_reactions_target_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )
  end
end
