defmodule Resdayn.Repo.Migrations.AddSpellEffects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:spells) do
      add(:effects, {:array, :map}, null: false, default: [])
    end
  end

  def down do
    alter table(:spells) do
      remove(:effects)
    end
  end
end
