defmodule Resdayn.Repo.Migrations.AddReferencesForDialogueResponses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:dialogue_responses, [:next_response_id])

    create index(:dialogue_responses, [:previous_response_id])
  end

  def down do
    drop_if_exists(index(:dialogue_responses, [:previous_response_id]))

    drop_if_exists(index(:dialogue_responses, [:next_response_id]))
  end
end
