defmodule Resdayn.Repo.Migrations.AddCellReferenceReferenceIdIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:cell_references, "cell_references_reference_id_fkey"))

    alter table(:cell_references) do
      modify(
        :reference_id,
        references(:referencable_objects,
          column: :id,
          name: "cell_references_reference_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create index(:cell_references, [:reference_id])
  end

  def down do
    drop_if_exists(index(:cell_references, [:reference_id]))

    drop(constraint(:cell_references, "cell_references_reference_id_fkey"))

    alter table(:cell_references) do
      modify(
        :reference_id,
        references(:referencable_objects,
          column: :id,
          name: "cell_references_reference_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end
end
