defmodule Resdayn.Repo.Migrations.AddItemLevelledLists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_items) do
      add(:item_levelled_list_id, :text)
    end

    create table(:item_levelled_lists, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
    end

    alter table(:inventory_items) do
      modify(
        :item_levelled_list_id,
        references(:item_levelled_lists,
          column: :id,
          name: "inventory_items_item_levelled_list_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:item_levelled_lists) do
      add(:chance_none, :bigint, null: false)
      add(:for_each_item, :boolean, null: false, default: false)
      add(:from_all_lower_levels, :boolean, null: false, default: false)
      add(:items, {:array, :map}, default: [])
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    alter table(:item_levelled_lists) do
      remove(:flags)
      remove(:items)
      remove(:from_all_lower_levels)
      remove(:for_each_item)
      remove(:chance_none)
    end

    drop(constraint(:inventory_items, "inventory_items_item_levelled_list_id_fkey"))

    alter table(:inventory_items) do
      modify(:item_levelled_list_id, :text)
    end

    drop(table(:item_levelled_lists))

    alter table(:inventory_items) do
      remove(:item_levelled_list_id)
    end
  end
end
