defmodule Resdayn.Repo.Migrations.CreateSearchIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:search_index, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:type, :text, null: false)
      add(:icon_filename, :text)
    end
  end

  def down do
    drop(table(:search_index))
  end
end
