defmodule Resdayn.Repo.Migrations.CleanupClaudeTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:tools), :tool_type, to: :type)

    alter table(:tools) do
      modify(:type, :text)
    end

    rename(table(:books), :content, to: :text)

    alter table(:books) do
      modify(:text, :text)
    end

    rename(table(:body_parts), :race, to: :race_id)

    rename(table(:body_parts), :body_part_type, to: :type)

    alter table(:body_parts) do
      modify(:type, :text)

      modify(
        :race_id,
        references(:races,
          column: :id,
          name: "body_parts_race_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    rename(table(:alchemy_apparatus), :apparatus_type, to: :type)

    alter table(:alchemy_apparatus) do
      modify(:type, :text)
    end
  end

  def down do
    alter table(:alchemy_apparatus) do
      modify(:apparatus_type, :text)
    end

    rename(table(:alchemy_apparatus), :type, to: :apparatus_type)

    drop(constraint(:body_parts, "body_parts_race_id_fkey"))

    alter table(:body_parts) do
      modify(:race, :text)
      modify(:body_part_type, :text)
    end

    rename(table(:body_parts), :type, to: :body_part_type)

    rename(table(:body_parts), :race_id, to: :race)

    alter table(:books) do
      modify(:content, :text)
    end

    rename(table(:books), :text, to: :content)

    alter table(:tools) do
      modify(:tool_type, :text)
    end

    rename(table(:tools), :type, to: :tool_type)
  end
end
