defmodule Resdayn.Repo.Migrations.CreateLights do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lights, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text)
      add(:nif_model_filename, :text)
      add(:icon_filename, :text)
      add(:weight, :float)
      add(:value, :bigint)
      add(:time, :bigint)
      add(:radius, :bigint)
      add(:color, :text)
      add(:dynamic, :boolean, default: false)
      add(:can_carry, :boolean, default: false)
      add(:negative, :boolean, default: false)
      add(:flicker, :boolean, default: false)
      add(:fire, :boolean, default: false)
      add(:off_by_default, :boolean, default: false)
      add(:flicker_slow, :boolean, default: false)
      add(:pulse, :boolean, default: false)
      add(:pulse_slow, :boolean, default: false)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "lights_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :sound_id,
        references(:sounds,
          column: :id,
          name: "lights_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:lights, "lights_script_id_fkey"))

    drop(constraint(:lights, "lights_sound_id_fkey"))

    drop(table(:lights))
  end
end
