defmodule Resdayn.Repo.Migrations.CreateGameSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:game_settings, primary_key: false) do
      add(:name, :text, null: false, primary_key: true)
      add(:value, :map)
      add(:flags, :map, null: false)
    end
  end

  def down do
    drop(table(:game_settings))
  end
end
