defmodule Resdayn.Repo.Migrations.CreateActivators do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:activators, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text)
      add(:nif_model_filename, :text)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "activators_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:activators, "activators_script_id_fkey"))

    drop(table(:activators))
  end
end
