defmodule Resdayn.Repo.Migrations.AddCreatureLevelledLists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:creature_levelled_lists, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:chance_none, :bigint, null: false)
      add(:for_each_item, :boolean, null: false, default: false)
      add(:from_all_lower_levels, :boolean, null: false, default: false)
      add(:creatures, {:array, :map}, default: [])
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    drop(table(:creature_levelled_lists))
  end
end
