defmodule Resdayn.Repo.Migrations.CreateStaticObjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:static_objects, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:nif_model_filename, :text)
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    drop(table(:static_objects))
  end
end
