defmodule Resdayn.Repo.Migrations.AddArmor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:armor, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:type, :text, null: false)
      add(:value, :bigint, null: false)
      add(:weight, :decimal, null: false)
      add(:nif_model_filename, :text, null: false)
      add(:icon_filename, :text, null: false)
      add(:enchantment_points, :bigint, null: false)
      add(:body_part_coverings, {:array, :map}, default: [])
      add(:health, :bigint, null: false)
      add(:armor_rating, :bigint, null: false)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "armor_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :enchantment_id,
        references(:enchantments,
          column: :id,
          name: "armor_enchantment_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:armor, "armor_script_id_fkey"))

    drop(constraint(:armor, "armor_enchantment_id_fkey"))

    drop(table(:armor))
  end
end
