defmodule Resdayn.Repo.Migrations.AddSoundGenerators do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sound_generators, primary_key: false) do
      add(
        :id,
        references(:referencable_objects,
          column: :id,
          name: "sound_generators_id_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      add(:creature_key, :text)
      add(:sound_type, :text, null: false)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :sound_id,
        references(:sounds,
          column: :id,
          name: "sound_generators_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:sound_generators, "sound_generators_id_fkey"))

    drop(constraint(:sound_generators, "sound_generators_sound_id_fkey"))

    drop(table(:sound_generators))
  end
end
