defmodule Resdayn.Repo.Migrations.ChangeDatafilePrimaryKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint("data_files", "data_files_pkey"))

    alter table(:data_files) do
      modify(:filename, :text, primary_key: false)
      add(:id, :text, null: false, primary_key: true)
    end
  end

  def down do
    drop(constraint("data_files", "data_files_pkey"))

    alter table(:data_files) do
      remove(:id)
      modify(:filename, :text, primary_key: true)
    end
  end
end
