defmodule Resdayn.Repo.Migrations.ConvertFlagsToImportableArray do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sounds) do
      remove(:flags)
      add(:flags, {:array, :text}, null: false, default: [])
    end

    alter table(:skills) do
      remove(:flags)
      add(:flags, {:array, :text}, null: false, default: [])
    end

    alter table(:scripts) do
      remove(:flags)
      add(:flags, {:array, :text}, null: false, default: [])
    end

    alter table(:magic_effects) do
      remove(:flags)
      add(:flags, {:array, :text}, null: false, default: [])
    end

    alter table(:global_variables) do
      remove(:flags)
      add(:flags, {:array, :text}, null: false, default: [])
    end

    alter table(:game_settings) do
      remove(:flags)
      add(:flags, {:array, :text}, null: false, default: [])
    end

    alter table(:data_files) do
      remove(:flags)
      add(:flags, {:array, :text}, null: false, default: [])
    end

    alter table(:attributes) do
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    alter table(:attributes) do
      remove(:flags)
    end

    alter table(:data_files) do
      remove(:flags)
      add(:flags, :map, default: nil)
    end

    alter table(:game_settings) do
      remove(:flags)
      add(:flags, :map, default: nil)
    end

    alter table(:global_variables) do
      remove(:flags)
      add(:flags, :map, default: nil)
    end

    alter table(:magic_effects) do
      remove(:flags)
      add(:flags, :map, default: nil)
    end

    alter table(:scripts) do
      remove(:flags)
      add(:flags, :map, default: nil)
    end

    alter table(:skills) do
      remove(:flags)
      add(:flags, :map, default: nil)
    end

    alter table(:sounds) do
      remove(:flags)
      add(:flags, :map, default: nil)
    end
  end
end
