defmodule Resdayn.Repo.Migrations.CreateDataFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:data_files, primary_key: false) do
      add(:filename, :text, null: false, primary_key: true)
      add(:description, :text)
      add(:version, :decimal, null: false)
      add(:master, :boolean, default: false)
      add(:company, :text)
      add(:dependencies, {:array, :map}, default: [])
      add(:flags, :map, null: false)
    end
  end

  def down do
    drop(table(:data_files))
  end
end
