defmodule Resdayn.Repo.Migrations.UnifiedObjectReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:referencable_objects, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:type, :text, null: false)
    end

    create unique_index(:referencable_objects, [:id, :type],
             name: "referencable_objects_unique_id_type_index"
           )

    alter table(:weapons) do
      modify(
        :id,
        references(:referencable_objects,
          column: :id,
          name: "weapons_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create index(:weapons, [:id])
  end

  def down do
    drop_if_exists(index(:weapons, [:id]))

    drop(constraint(:weapons, "weapons_id_fkey"))

    alter table(:weapons) do
      modify(:id, :text)
    end

    drop_if_exists(
      unique_index(:referencable_objects, [:id, :type],
        name: "referencable_objects_unique_id_type_index"
      )
    )

    drop(table(:referencable_objects))
  end
end
