defmodule Resdayn.Repo.Migrations.CreateScripts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scripts, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:text, :text, null: false)
      add(:local_variables, {:array, :text}, default: [])
      add(:start_script, :boolean, default: false)
      add(:flags, :map, null: false)
    end
  end

  def down do
    drop(table(:scripts))
  end
end
