defmodule Resdayn.Repo.Migrations.PromoteAppliedMagicEffects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:spells) do
      remove(:effects)
    end

    alter table(:enchantments) do
      remove(:effects)
    end

    alter table(:potions) do
      remove(:effects)
    end

    create table(:applied_magic_effects, primary_key: false) do
      add(:parent_type, :text, null: false, primary_key: true)
      add(:parent_id, :text, null: false, primary_key: true)
      add(:index, :bigint, null: false, primary_key: true)
      add(:duration, :bigint, null: false)
      add(:magnitude, {:array, :integer}, null: false)
      add(:range, :text, null: false)
      add(:area, :bigint, null: false)
      add(:flags, {:array, :text}, null: false, default: [])
      add(:source_file_ids, {:array, :text}, null: false, default: [])

      add(
        :magic_effect_id,
        references(:magic_effects,
          column: :id,
          name: "applied_magic_effects_magic_effect_id_fkey",
          type: :text,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:applied_magic_effects, "applied_magic_effects_magic_effect_id_fkey"))

    drop(table(:applied_magic_effects))

    alter table(:potions) do
      add(:effects, {:array, :map}, null: false, default: [])
    end

    alter table(:enchantments) do
      add(:effects, {:array, :map}, null: false, default: [])
    end

    alter table(:spells) do
      add(:effects, {:array, :map}, null: false, default: [])
    end
  end
end
