defmodule Resdayn.Repo.Migrations.AddDescriptionGmstToAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:attributes) do
      add(
        :description_game_setting_id,
        references(:game_settings,
          column: :name,
          name: "attributes_description_game_setting_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:attributes, "attributes_description_game_setting_id_fkey"))

    alter table(:attributes) do
      remove(:description_game_setting_id)
    end
  end
end
