defmodule Resdayn.Repo.Migrations.CreateSounds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sounds, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:filename, :text)
      add(:volume, :bigint, null: false)
      add(:range, {:array, :integer}, null: false)
      add(:flags, :map, null: false)
    end
  end

  def down do
    drop(table(:sounds))
  end
end
