defmodule Resdayn.Repo.Migrations.SourceFileTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:spells) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:creature_levelled_lists) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:sound_generators) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:races) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:inventory_items) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:cell_references) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:activators) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:scripts) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:journal_entries) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:creatures) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:books) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:static_objects) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:skills) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:miscellaneous_items) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:birthsigns) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:global_variables) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:game_settings) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:clothing) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:tools) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:lights) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:regions) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:armor) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:attributes) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:quests) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:doors) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:data_files) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:cells) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:containers) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:weapons) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:dialogue_topics) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:magic_effects) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:npcs) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    create table(:import_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:event_type, :text, null: false)
      add(:resource_type, :text, null: false)
      add(:resource_id, :text, null: false)

      add(
        :source_file_id,
        references(:data_files,
          column: :filename,
          name: "import_events_source_file_id_fkey",
          type: :text,
          prefix: "public"
        ),
        null: false
      )

      add(:changes, :map, null: false, default: %{})

      add(:occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    alter table(:item_levelled_lists) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:alchemy_apparatus) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:classes) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:sounds) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:body_parts) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:ingredients) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:factions) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:enchantments) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end

    alter table(:potions) do
      add(:source_file_ids, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    alter table(:potions) do
      remove(:source_file_ids)
    end

    alter table(:enchantments) do
      remove(:source_file_ids)
    end

    alter table(:factions) do
      remove(:source_file_ids)
    end

    alter table(:ingredients) do
      remove(:source_file_ids)
    end

    alter table(:body_parts) do
      remove(:source_file_ids)
    end

    alter table(:sounds) do
      remove(:source_file_ids)
    end

    alter table(:classes) do
      remove(:source_file_ids)
    end

    alter table(:alchemy_apparatus) do
      remove(:source_file_ids)
    end

    alter table(:item_levelled_lists) do
      remove(:source_file_ids)
    end

    drop(constraint(:import_events, "import_events_source_file_id_fkey"))

    drop(table(:import_events))

    alter table(:npcs) do
      remove(:source_file_ids)
    end

    alter table(:magic_effects) do
      remove(:source_file_ids)
    end

    alter table(:dialogue_topics) do
      remove(:source_file_ids)
    end

    alter table(:weapons) do
      remove(:source_file_ids)
    end

    alter table(:containers) do
      remove(:source_file_ids)
    end

    alter table(:cells) do
      remove(:source_file_ids)
    end

    alter table(:data_files) do
      remove(:source_file_ids)
    end

    alter table(:doors) do
      remove(:source_file_ids)
    end

    alter table(:quests) do
      remove(:source_file_ids)
    end

    alter table(:attributes) do
      remove(:source_file_ids)
    end

    alter table(:armor) do
      remove(:source_file_ids)
    end

    alter table(:regions) do
      remove(:source_file_ids)
    end

    alter table(:lights) do
      remove(:source_file_ids)
    end

    alter table(:tools) do
      remove(:source_file_ids)
    end

    alter table(:clothing) do
      remove(:source_file_ids)
    end

    alter table(:game_settings) do
      remove(:source_file_ids)
    end

    alter table(:global_variables) do
      remove(:source_file_ids)
    end

    alter table(:birthsigns) do
      remove(:source_file_ids)
    end

    alter table(:miscellaneous_items) do
      remove(:source_file_ids)
    end

    alter table(:skills) do
      remove(:source_file_ids)
    end

    alter table(:static_objects) do
      remove(:source_file_ids)
    end

    alter table(:books) do
      remove(:source_file_ids)
    end

    alter table(:creatures) do
      remove(:source_file_ids)
    end

    alter table(:journal_entries) do
      remove(:source_file_ids)
    end

    alter table(:scripts) do
      remove(:source_file_ids)
    end

    alter table(:activators) do
      remove(:source_file_ids)
    end

    alter table(:cell_references) do
      remove(:source_file_ids)
    end

    alter table(:inventory_items) do
      remove(:source_file_ids)
    end

    alter table(:races) do
      remove(:source_file_ids)
    end

    alter table(:sound_generators) do
      remove(:source_file_ids)
    end

    alter table(:creature_levelled_lists) do
      remove(:source_file_ids)
    end

    alter table(:spells) do
      remove(:source_file_ids)
    end
  end
end
