defmodule Resdayn.Repo.Migrations.CreateTools do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tools, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:tool_type, :text, null: false)
      add(:nif_model_filename, :text)
      add(:icon_filename, :text)
      add(:weight, :float)
      add(:value, :bigint)
      add(:uses, :bigint)
      add(:quality, :float)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "tools_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:tools, "tools_script_id_fkey"))

    drop(table(:tools))
  end
end
