defmodule Resdayn.Repo.Migrations.CreateAlchemyApparatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alchemy_apparatus, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:apparatus_type, :text, null: false)
      add(:nif_model_filename, :text)
      add(:icon_filename, :text)
      add(:weight, :float)
      add(:value, :bigint)
      add(:quality, :float)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "alchemy_apparatus_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:alchemy_apparatus, "alchemy_apparatus_script_id_fkey"))

    drop(table(:alchemy_apparatus))
  end
end
