defmodule Resdayn.Repo.Migrations.AddMissingIngredientEffects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingredient_effects, primary_key: false) do
      add(
        :ingredient_id,
        references(:ingredients,
          column: :id,
          name: "ingredient_effects_ingredient_id_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      add(
        :magic_effect_id,
        references(:magic_effects,
          column: :id,
          name: "ingredient_effects_magic_effect_id_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )
    end
  end

  def down do
    drop(constraint(:ingredient_effects, "ingredient_effects_ingredient_id_fkey"))

    drop(constraint(:ingredient_effects, "ingredient_effects_magic_effect_id_fkey"))

    drop(table(:ingredient_effects))
  end
end
