defmodule Resdayn.Repo.Migrations.AddDoors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:doors, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text)
      add(:nif_model_filename, :text, null: false)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "doors_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :open_sound_id,
        references(:sounds,
          column: :id,
          name: "doors_open_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :close_sound_id,
        references(:sounds,
          column: :id,
          name: "doors_close_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:doors, "doors_script_id_fkey"))

    drop(constraint(:doors, "doors_open_sound_id_fkey"))

    drop(constraint(:doors, "doors_close_sound_id_fkey"))

    drop(table(:doors))
  end
end
