defmodule Resdayn.Repo.Migrations.CreateSpells do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:spells, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:type, :text, null: false)
      add(:cost, :bigint, null: false)
      add(:spell_flags, {:array, :text}, null: false, default: [])
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    drop(table(:spells))
  end
end
