defmodule Resdayn.Repo.Migrations.CreateMiscellaneousItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:miscellaneous_items, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:value, :bigint, null: false)
      add(:weight, :decimal, null: false)
      add(:nif_model_filename, :text, null: false)
      add(:icon_filename, :text, null: false)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "miscellaneous_items_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:miscellaneous_items, "miscellaneous_items_script_id_fkey"))

    drop(table(:miscellaneous_items))
  end
end
