defmodule Resdayn.Repo.Migrations.CreateNpcSkillValues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:npcs) do
      remove(:skills)
    end

    create table(:npc_skill_values, primary_key: false) do
      add(:value, :bigint, null: false)

      add(
        :npc_id,
        references(:npcs,
          column: :id,
          name: "npc_skill_values_npc_id_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      add(
        :skill_id,
        references(:skills,
          column: :id,
          name: "npc_skill_values_skill_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )
    end
  end

  def down do
    drop(constraint(:npc_skill_values, "npc_skill_values_npc_id_fkey"))

    drop(constraint(:npc_skill_values, "npc_skill_values_skill_id_fkey"))

    drop(table(:npc_skill_values))

    alter table(:npcs) do
      add(:skills, {:array, :map}, null: false, default: [])
    end
  end
end
