defmodule Resdayn.Repo.Migrations.CreateQuests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:journal_entries, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:index, :bigint, null: false)
      add(:content, :text)
      add(:finishes_quest, :boolean, default: false)
      add(:restarts_quest, :boolean, default: false)
      add(:flags, {:array, :text}, null: false, default: [])
      add(:quest_id, :text)
    end

    create table(:quests, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
    end

    alter table(:journal_entries) do
      modify(
        :quest_id,
        references(:quests,
          column: :id,
          name: "journal_entries_quest_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:quests) do
      add(:name, :text, null: false)
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    alter table(:quests) do
      remove(:flags)
      remove(:name)
    end

    drop(constraint(:journal_entries, "journal_entries_quest_id_fkey"))

    alter table(:journal_entries) do
      modify(:quest_id, :text)
    end

    drop(table(:quests))

    drop(table(:journal_entries))
  end
end
