defmodule Resdayn.Repo.Migrations.AddClassToArmor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:armor) do
      add(:class, :text, null: false)
    end
  end

  def down do
    alter table(:armor) do
      remove(:class)
    end
  end
end
