defmodule Resdayn.Repo.Migrations.UpdateLightFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lights) do
      remove(:pulse_slow)
      remove(:pulse)
      remove(:flicker_slow)
      remove(:off_by_default)
      remove(:fire)
      remove(:flicker)
      remove(:negative)
      remove(:can_carry)
      remove(:dynamic)
      add(:light_flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    alter table(:lights) do
      remove(:light_flags)
      add(:dynamic, :boolean, default: false)
      add(:can_carry, :boolean, default: false)
      add(:negative, :boolean, default: false)
      add(:flicker, :boolean, default: false)
      add(:fire, :boolean, default: false)
      add(:off_by_default, :boolean, default: false)
      add(:flicker_slow, :boolean, default: false)
      add(:pulse, :boolean, default: false)
      add(:pulse_slow, :boolean, default: false)
    end
  end
end
