defmodule Resdayn.Repo.Migrations.CreateGlobalVariables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:global_variables, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:value, :map, null: false)
      add(:flags, :map, null: false)
    end
  end

  def down do
    drop(table(:global_variables))
  end
end
