defmodule Resdayn.Repo.Migrations.AddReferenceForResponseTopicId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:dialogue_responses, [:id, :topic_id])

    drop(constraint(:dialogue_responses, "dialogue_responses_topic_id_fkey"))

    alter table(:dialogue_responses) do
      modify(
        :topic_id,
        references(:dialogue_topics,
          column: :id,
          name: "dialogue_responses_topic_id_fkey",
          type: :text,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end
  end

  def down do
    drop(constraint(:dialogue_responses, "dialogue_responses_topic_id_fkey"))

    alter table(:dialogue_responses) do
      modify(
        :topic_id,
        references(:dialogue_topics,
          column: :id,
          name: "dialogue_responses_topic_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:dialogue_responses, [:id, :topic_id]))
  end
end
