defmodule Resdayn.Repo.Migrations.CreateBooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:books, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:value, :bigint, null: false)
      add(:weight, :decimal, null: false)
      add(:nif_model_filename, :text, null: false)
      add(:icon_filename, :text)
      add(:enchantment_points, :bigint, null: false)
      add(:scroll, :boolean, default: false)
      add(:content, :text)
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "books_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :enchantment_id,
        references(:enchantments,
          column: :id,
          name: "books_enchantment_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :skill_id,
        references(:skills,
          column: :id,
          name: "books_skill_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:books, "books_script_id_fkey"))

    drop(constraint(:books, "books_enchantment_id_fkey"))

    drop(constraint(:books, "books_skill_id_fkey"))

    drop(table(:books))
  end
end
