defmodule Resdayn.Repo.Migrations.CreateBodyParts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:body_parts, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:nif_model_filename, :text)
      add(:race, :text)
      add(:body_part_type, :text, null: false)
      add(:equipment_type, :text, null: false)
      add(:vampire, :boolean, default: false)
      add(:body_part_flags, {:array, :text}, null: false, default: [])
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    drop(table(:body_parts))
  end
end
