defmodule Resdayn.Repo.Migrations.AddWeapons do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:weapons, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:name, :text)
      add(:type, :text, null: false)
      add(:value, :bigint, null: false)
      add(:weight, :decimal, null: false)
      add(:nif_model_filename, :text, null: false)
      add(:icon_filename, :text)
      add(:enchantment_points, :bigint, null: false)
      add(:health, :bigint, null: false)
      add(:speed, :float, null: false)
      add(:reach, :float, null: false)
      add(:chop_magnitude, {:array, :integer}, null: false)
      add(:slash_magnitude, {:array, :integer}, null: false)
      add(:thrust_magnitude, {:array, :integer}, null: false)
      add(:weapon_flags, {:array, :text}, default: [])
      add(:flags, {:array, :text}, null: false, default: [])

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "weapons_script_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :enchantment_id,
        references(:enchantments,
          column: :id,
          name: "weapons_enchantment_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:weapons, "weapons_script_id_fkey"))

    drop(constraint(:weapons, "weapons_enchantment_id_fkey"))

    drop(table(:weapons))
  end
end
