defmodule Resdayn.Repo.Migrations.DropRaceSpellBonusesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:race_spell_bonuses, "race_spell_bonuses_race_id_fkey"))
    drop(constraint(:race_spell_bonuses, "race_spell_bonuses_spell_id_fkey"))
    drop(table(:race_spell_bonuses))

    alter table(:races) do
      add(:special_spells, {:array, :map}, null: false, default: [])
    end
  end

  def down do
    alter table(:races) do
      remove(:special_spells)
    end

    create table(:race_spell_bonuses, primary_key: false) do
      add(
        :race_id,
        references(:races,
          column: :id,
          name: "race_spell_bonuses_race_id_fkey",
          type: :text,
          prefix: "public",
          on_delete: :delete_all
        ),
        primary_key: true,
        null: false
      )

      add(
        :spell_id,
        references(:spells,
          column: :id,
          name: "race_spell_bonuses_spell_id_fkey",
          type: :text,
          prefix: "public",
          on_delete: :delete_all
        ),
        primary_key: true,
        null: false
      )
    end
  end
end
