defmodule Resdayn.Repo.Migrations.RenameGameSettingsName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:game_settings), :name, to: :id)

    alter table(:game_settings) do
      modify(:id, :text)
    end

    drop(constraint(:attributes, "attributes_description_game_setting_id_fkey"))

    alter table(:attributes) do
      modify(
        :description_game_setting_id,
        references(:game_settings,
          column: :id,
          name: "attributes_description_game_setting_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    drop(constraint(:magic_effects, "magic_effects_game_setting_id_fkey"))

    alter table(:magic_effects) do
      modify(
        :game_setting_id,
        references(:game_settings,
          column: :id,
          name: "magic_effects_game_setting_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:magic_effects, "magic_effects_game_setting_id_fkey"))

    alter table(:magic_effects) do
      modify(
        :game_setting_id,
        references(:game_settings,
          column: :name,
          name: "magic_effects_game_setting_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    drop(constraint(:attributes, "attributes_description_game_setting_id_fkey"))

    alter table(:attributes) do
      modify(
        :description_game_setting_id,
        references(:game_settings,
          column: :name,
          name: "attributes_description_game_setting_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:game_settings) do
      modify(:name, :text)
    end

    rename(table(:game_settings), :id, to: :name)
  end
end
