defmodule Resdayn.Repo.Migrations.CreateSkills do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skills, primary_key: false) do
      add(:id, :bigint, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text, null: false)
      add(:uses, {:array, :float}, null: false)
      add(:specialization, :text, null: false)
      add(:flags, :map, null: false)

      add(
        :attribute_id,
        references(:attributes,
          column: :id,
          name: "skills_attribute_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:skills, "skills_attribute_id_fkey"))

    drop(table(:skills))
  end
end
