defmodule Resdayn.Repo.Migrations.PromoteMagicEffects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:magic_effect_templates, primary_key: false) do
      add(:id, :bigint, null: false, primary_key: true)
      add(:description, :text)
      add(:size, :float, null: false)
      add(:color, :text, null: false)
      add(:speed, :float, null: false)
      add(:base_cost, :float, null: false)
      add(:size_cap, :float, null: false)
      add(:icon_filename, :text, null: false)
      add(:particle_texture_filename, :text, null: false)
      add(:area_visual, :text, default: "VFX_DefaultArea")
      add(:bolt_visual, :text, default: "VFX_DefaultBolt")
      add(:casting_visual, :text, default: "VFX_DefaultCast")
      add(:hit_visual, :text, default: "VFX_DefaultHit")
      add(:allows_spellmaking, :boolean, null: false)
      add(:allows_enchanting, :boolean, null: false)
      add(:negative_light, :boolean, null: false)
      add(:flags, {:array, :text}, null: false, default: [])
      add(:source_file_ids, {:array, :text}, null: false, default: [])

      add(
        :game_setting_id,
        references(:game_settings,
          column: :id,
          name: "magic_effect_templates_game_setting_id_fkey",
          type: :text,
          prefix: "public"
        ),
        null: false
      )

      add(
        :magic_school_id,
        references(:skills,
          column: :id,
          name: "magic_effect_templates_magic_school_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )

      add(
        :area_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effect_templates_area_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :bolt_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effect_templates_bolt_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :casting_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effect_templates_casting_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :hit_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effect_templates_hit_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:magic_effects) do
      remove(:hit_sound_id)
      remove(:casting_sound_id)
      remove(:bolt_sound_id)
      remove(:area_sound_id)
      remove(:game_setting_id)
      remove(:source_file_ids)
      remove(:flags)
      remove(:negative_light)
      remove(:allows_enchanting)
      remove(:allows_spellmaking)
      remove(:hit_visual)
      remove(:casting_visual)
      remove(:bolt_visual)
      remove(:area_visual)
      remove(:particle_texture_filename)
      remove(:icon_filename)
      remove(:size_cap)
      remove(:base_cost)
      remove(:speed)
      remove(:color)
      remove(:size)
      remove(:description)
      modify(:skill_id, :bigint, null: true)
      modify(:id, :text)

      add(
        :template_id,
        references(:magic_effect_templates,
          column: :id,
          name: "magic_effects_template_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )

      add(
        :attribute_id,
        references(:attributes,
          column: :id,
          name: "magic_effects_attribute_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )
    end

    alter table(:ingredients) do
      remove(:effects)
    end
  end

  def down do
    alter table(:ingredients) do
      add(:effects, {:array, :map}, null: false, default: [])
    end

    drop(constraint(:magic_effects, "magic_effects_template_id_fkey"))

    drop(constraint(:magic_effects, "magic_effects_attribute_id_fkey"))

    alter table(:magic_effects) do
      remove(:attribute_id)
      remove(:template_id)
      modify(:id, :bigint)
      modify(:skill_id, :bigint, null: false)
      add(:description, :text)
      add(:size, :float, null: false)
      add(:color, :text, null: false)
      add(:speed, :float, null: false)
      add(:base_cost, :float, null: false)
      add(:size_cap, :float, null: false)
      add(:icon_filename, :text, null: false)
      add(:particle_texture_filename, :text, null: false)
      add(:area_visual, :text, default: "VFX_DefaultArea")
      add(:bolt_visual, :text, default: "VFX_DefaultBolt")
      add(:casting_visual, :text, default: "VFX_DefaultCast")
      add(:hit_visual, :text, default: "VFX_DefaultHit")
      add(:allows_spellmaking, :boolean, null: false)
      add(:allows_enchanting, :boolean, null: false)
      add(:negative_light, :boolean, null: false)
      add(:flags, {:array, :text}, null: false, default: [])
      add(:source_file_ids, {:array, :text}, null: false, default: [])

      add(
        :game_setting_id,
        references(:game_settings,
          column: :id,
          name: "magic_effects_game_setting_id_fkey",
          type: :text,
          prefix: "public"
        ),
        null: false
      )

      add(
        :area_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effects_area_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :bolt_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effects_bolt_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :casting_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effects_casting_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )

      add(
        :hit_sound_id,
        references(:sounds,
          column: :id,
          name: "magic_effects_hit_sound_id_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    drop(constraint(:magic_effect_templates, "magic_effect_templates_game_setting_id_fkey"))

    drop(constraint(:magic_effect_templates, "magic_effect_templates_magic_school_id_fkey"))

    drop(constraint(:magic_effect_templates, "magic_effect_templates_area_sound_id_fkey"))

    drop(constraint(:magic_effect_templates, "magic_effect_templates_bolt_sound_id_fkey"))

    drop(constraint(:magic_effect_templates, "magic_effect_templates_casting_sound_id_fkey"))

    drop(constraint(:magic_effect_templates, "magic_effect_templates_hit_sound_id_fkey"))

    drop(table(:magic_effect_templates))
  end
end
