defmodule Resdayn.Repo.Migrations.ConvertActorInvolvementDialogueTopicToRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:actor_involvements) do
      modify(
        :dialogue_response_topic_id,
        references(:dialogue_topics,
          column: :id,
          name: "actor_involvements_dialogue_response_topic_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    create index(:actor_involvements, [:dialogue_response_topic_id])
  end

  def down do
    drop_if_exists(index(:actor_involvements, [:dialogue_response_topic_id]))

    drop(constraint(:actor_involvements, "actor_involvements_dialogue_response_topic_id_fkey"))

    alter table(:actor_involvements) do
      modify(:dialogue_response_topic_id, :citext)
    end
  end
end
