defmodule Resdayn.Repo.Migrations.RenameQuestsToQuestVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:quests), to: table(:quest_versions))

    rename(table(:journal_entries), :quest_id, to: :quest_version_id)

    drop(constraint(:journal_entries, "journal_entries_quest_id_fkey"))

    alter table(:journal_entries) do
      modify(
        :quest_version_id,
        references(:quest_versions,
          column: :id,
          name: "journal_entries_quest_version_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    drop(constraint(:quest_versions, "quests_faction_id_fkey"))

    alter table(:quest_versions) do
      modify(
        :faction_id,
        references(:factions,
          column: :id,
          name: "quest_versions_faction_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:quest_versions, "quest_versions_faction_id_fkey"))

    alter table(:quest_versions) do
      modify(
        :faction_id,
        references(:factions,
          column: :id,
          name: "quests_faction_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    drop(constraint(:journal_entries, "journal_entries_quest_version_id_fkey"))

    alter table(:journal_entries) do
      modify(
        :quest_version_id,
        references(:quests,
          column: :id,
          name: "journal_entries_quest_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    rename(table(:journal_entries), :quest_version_id, to: :quest_id)

    rename(table(:quest_versions), to: table(:quests))
  end
end
