defmodule Resdayn.Repo.Migrations.CreateOverrides do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tools) do
      modify(:quality, :float, null: false)
      modify(:uses, :bigint, null: false)
      modify(:value, :bigint, null: false)
      modify(:weight, :float, null: false)
      modify(:icon_filename, :text, null: false)
      modify(:nif_model_filename, :text, null: false)
    end

    create table(:overrides, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:record_id, :citext, null: false)
      add(:resource_type, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:overrides, [:record_id, :resource_type],
             name: "overrides_unique_record_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:overrides, [:record_id, :resource_type],
        name: "overrides_unique_record_index"
      )
    )

    drop(table(:overrides))

    alter table(:tools) do
      modify(:nif_model_filename, :text, null: true)
      modify(:icon_filename, :text, null: true)
      modify(:weight, :float, null: true)
      modify(:value, :bigint, null: true)
      modify(:uses, :bigint, null: true)
      modify(:quality, :float, null: true)
    end
  end
end
