defmodule Resdayn.Repo.Migrations.ReplaceTransitionFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transitions) do
      remove(:is_quest_finish)
      remove(:is_quest_start)
      add(:flags, {:array, :text}, null: false, default: [])
    end
  end

  def down do
    alter table(:transitions) do
      remove(:flags)
      add(:is_quest_start, :boolean)
      add(:is_quest_finish, :boolean)
    end
  end
end
