defmodule Resdayn.Repo.Migrations.AddNpcInvolvement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:npc_involvements, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:reason, :text, null: false)
      add(:dialogue_response_topic_id, :citext)

      add(
        :quest_id,
        references(:quests,
          column: :id,
          name: "npc_involvements_quest_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(
        :quest_version_id,
        references(:quest_versions,
          column: :id,
          name: "npc_involvements_quest_version_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(
        :npc_id,
        references(:npcs,
          column: :id,
          name: "npc_involvements_npc_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(
        :dialogue_response_id,
        references(:dialogue_responses,
          column: :id,
          with: [dialogue_response_topic_id: :topic_id],
          name: "npc_involvements_dialogue_response_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "npc_involvements_script_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    create unique_index(
             :npc_involvements,
             [
               :quest_id,
               :quest_version_id,
               :npc_id,
               :reason,
               :dialogue_response_id,
               :dialogue_response_topic_id,
               :script_id
             ], name: "npc_involvements_unique_involvement_index", nulls_distinct: false)

    create constraint(:npc_involvements, :exactly_one_source,
             check: """
               (
               (dialogue_response_id IS NOT NULL
                 AND dialogue_response_topic_id IS NOT NULL
                 AND script_id IS NULL)
               OR
               (dialogue_response_id IS NULL
                 AND dialogue_response_topic_id IS NULL
                 AND script_id IS NOT NULL)
             )

             """
           )
  end

  def down do
    drop_if_exists(constraint(:npc_involvements, :exactly_one_source))

    drop(constraint(:npc_involvements, "npc_involvements_quest_id_fkey"))

    drop(constraint(:npc_involvements, "npc_involvements_quest_version_id_fkey"))

    drop(constraint(:npc_involvements, "npc_involvements_npc_id_fkey"))

    drop(constraint(:npc_involvements, "npc_involvements_dialogue_response_id_fkey"))

    drop(constraint(:npc_involvements, "npc_involvements_script_id_fkey"))

    drop_if_exists(
      unique_index(
        :npc_involvements,
        [
          :quest_id,
          :quest_version_id,
          :npc_id,
          :reason,
          :dialogue_response_id,
          :dialogue_response_topic_id,
          :script_id
        ], name: "npc_involvements_unique_involvement_index")
    )

    drop(table(:npc_involvements))
  end
end
