defmodule Resdayn.Repo.Migrations.AddNotNullConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:creatures) do
      modify(:name, :text, null: false)
    end

    alter table(:static_objects) do
      modify(:nif_model_filename, :text, null: false)
    end

    alter table(:containers) do
      modify(:nif_model_filename, :text, null: false)
    end

    alter table(:npcs) do
      modify(:name, :text, null: false)
    end

    alter table(:alchemy_apparatus) do
      modify(:quality, :float, null: false)
      modify(:value, :bigint, null: false)
      modify(:weight, :float, null: false)
      modify(:icon_filename, :text, null: false)
      modify(:nif_model_filename, :text, null: false)
    end
  end

  def down do
    alter table(:alchemy_apparatus) do
      modify(:nif_model_filename, :text, null: true)
      modify(:icon_filename, :text, null: true)
      modify(:weight, :float, null: true)
      modify(:value, :bigint, null: true)
      modify(:quality, :float, null: true)
    end

    alter table(:npcs) do
      modify(:name, :text, null: true)
    end

    alter table(:containers) do
      modify(:nif_model_filename, :text, null: true)
    end

    alter table(:static_objects) do
      modify(:nif_model_filename, :text, null: true)
    end

    alter table(:creatures) do
      modify(:name, :text, null: true)
    end
  end
end
