defmodule Resdayn.Repo.Migrations.AddTransitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transitions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:target_index, :bigint, null: false)
      add(:dialogue_response_topic_id, :citext)
      add(:from_min, :bigint)
      add(:from_max, :bigint)
      add(:is_quest_start, :boolean)
      add(:is_quest_finish, :boolean)

      add(
        :quest_id,
        references(:quests,
          column: :id,
          name: "transitions_quest_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(
        :quest_version_id,
        references(:quest_versions,
          column: :id,
          name: "transitions_quest_version_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(
        :dialogue_response_id,
        references(:dialogue_responses,
          column: :id,
          with: [dialogue_response_topic_id: :topic_id],
          name: "transitions_dialogue_response_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      add(
        :script_id,
        references(:scripts,
          column: :id,
          name: "transitions_script_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    create unique_index(
             :transitions,
             [
               :quest_id,
               :quest_version_id,
               :dialogue_response_id,
               :dialogue_response_topic_id,
               :script_id,
               :target_index
             ], name: "transitions_unique_transition_index", nulls_distinct: false)

    create constraint(:transitions, :exactly_one_source,
             check: """
               (
               (dialogue_response_id IS NOT NULL AND dialogue_response_topic_id IS NOT NULL AND script_id IS NULL)
               OR
               (dialogue_response_id IS NULL AND dialogue_response_topic_id IS NULL AND script_id IS NOT NULL)
             )

             """
           )
  end

  def down do
    drop_if_exists(constraint(:transitions, :exactly_one_source))

    drop(constraint(:transitions, "transitions_quest_id_fkey"))

    drop(constraint(:transitions, "transitions_quest_version_id_fkey"))

    drop(constraint(:transitions, "transitions_dialogue_response_id_fkey"))

    drop(constraint(:transitions, "transitions_script_id_fkey"))

    drop_if_exists(
      unique_index(
        :transitions,
        [
          :quest_id,
          :quest_version_id,
          :dialogue_response_id,
          :dialogue_response_topic_id,
          :script_id,
          :target_index
        ], name: "transitions_unique_transition_index")
    )

    drop(table(:transitions))
  end
end
