defmodule Resdayn.Repo.Migrations.AddActorInvolvementActorQuestIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:actor_involvements, [:creature_id, :quest_id], where: "creature_id IS NOT NULL")

    create index(:actor_involvements, [:npc_id, :quest_id], where: "npc_id IS NOT NULL")
  end

  def down do
    drop_if_exists(index(:actor_involvements, [:npc_id, :quest_id]))

    drop_if_exists(index(:actor_involvements, [:creature_id, :quest_id]))
  end
end
