defmodule Resdayn.Repo.Migrations.DedupeLevelledListEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:item_levelled_lists) do
      remove(:items)
      add(:entries, {:array, :map}, default: [])
    end

    alter table(:creature_levelled_lists) do
      remove(:creatures)
      remove(:for_each_item)
      add(:entries, {:array, :map}, default: [])
    end
  end

  def down do
    alter table(:creature_levelled_lists) do
      remove(:entries)
      add(:for_each_item, :boolean, null: false, default: false)
      add(:creatures, {:array, :map}, default: [])
    end

    alter table(:item_levelled_lists) do
      remove(:entries)
      add(:items, {:array, :map}, default: [])
    end
  end
end
