defmodule Resdayn.Repo.Migrations.AddFactionIdToQuests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:quests) do
      add(
        :faction_id,
        references(:factions,
          column: :id,
          name: "quests_faction_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:quests, "quests_faction_id_fkey"))

    alter table(:quests) do
      remove(:faction_id)
    end
  end
end
