defmodule Resdayn.Repo.Migrations.RenameNpcInvolvementToActorInvolvement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:npc_involvements), to: table(:actor_involvements))

    drop(constraint(:actor_involvements, "npc_involvements_script_id_fkey"))

    drop(constraint(:actor_involvements, "npc_involvements_dialogue_response_id_fkey"))

    drop(constraint(:actor_involvements, "npc_involvements_npc_id_fkey"))

    drop(constraint(:actor_involvements, "npc_involvements_quest_version_id_fkey"))

    drop(constraint(:actor_involvements, "npc_involvements_quest_id_fkey"))

    alter table(:actor_involvements) do
      add(
        :creature_id,
        references(:creatures,
          column: :id,
          name: "actor_involvements_creature_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    drop_if_exists(
      unique_index(
        :actor_involvements,
        [
          :quest_id,
          :quest_version_id,
          :npc_id,
          :reason,
          :dialogue_response_id,
          :dialogue_response_topic_id,
          :script_id
        ], name: "npc_involvements_unique_involvement_index")
    )

    create unique_index(
             :actor_involvements,
             [
               :quest_id,
               :quest_version_id,
               :npc_id,
               :creature_id,
               :reason,
               :dialogue_response_id,
               :dialogue_response_topic_id,
               :script_id
             ], name: "actor_involvements_unique_involvement_index", nulls_distinct: false)

    alter table(:actor_involvements) do
      modify(
        :quest_id,
        references(:quests,
          column: :id,
          name: "actor_involvements_quest_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :quest_version_id,
        references(:quest_versions,
          column: :id,
          name: "actor_involvements_quest_version_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :npc_id,
        references(:npcs,
          column: :id,
          name: "actor_involvements_npc_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        ), null: true)

      modify(
        :dialogue_response_id,
        references(:dialogue_responses,
          column: :id,
          with: [dialogue_response_topic_id: :topic_id],
          name: "actor_involvements_dialogue_response_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :script_id,
        references(:scripts,
          column: :id,
          name: "actor_involvements_script_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    drop_if_exists(constraint(:actor_involvements, :exactly_one_source))

    create constraint(:actor_involvements, :exactly_one_subject,
             check: """
               (npc_id IS NOT NULL) <> (creature_id IS NOT NULL)
             """
           )

    create constraint(:actor_involvements, :exactly_one_source,
             check: """
               (
               (dialogue_response_id IS NOT NULL AND dialogue_response_topic_id IS NOT NULL AND script_id IS NULL)
               OR
               (dialogue_response_id IS NULL AND dialogue_response_topic_id IS NULL AND script_id IS NOT NULL)
             )

             """
           )
  end

  def down do
    drop_if_exists(constraint(:actor_involvements, :exactly_one_source))

    drop_if_exists(constraint(:actor_involvements, :exactly_one_subject))

    create constraint(:actor_involvements, :exactly_one_source,
             check: """
               (
               (dialogue_response_id IS NOT NULL
                 AND dialogue_response_topic_id IS NOT NULL
                 AND script_id IS NULL)
               OR
               (dialogue_response_id IS NULL
                 AND dialogue_response_topic_id IS NULL
                 AND script_id IS NOT NULL)
             )

             """
           )

    drop(constraint(:actor_involvements, "actor_involvements_creature_id_fkey"))

    drop(constraint(:actor_involvements, "actor_involvements_quest_id_fkey"))

    drop(constraint(:actor_involvements, "actor_involvements_quest_version_id_fkey"))

    drop(constraint(:actor_involvements, "actor_involvements_npc_id_fkey"))

    drop(constraint(:actor_involvements, "actor_involvements_dialogue_response_id_fkey"))

    drop(constraint(:actor_involvements, "actor_involvements_script_id_fkey"))

    alter table(:actor_involvements) do
      modify(
        :script_id,
        references(:scripts,
          column: :id,
          name: "npc_involvements_script_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :dialogue_response_id,
        references(:dialogue_responses,
          column: :id,
          with: [dialogue_response_topic_id: :topic_id],
          name: "npc_involvements_dialogue_response_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :npc_id,
        references(:npcs,
          column: :id,
          name: "npc_involvements_npc_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      modify(
        :quest_version_id,
        references(:quest_versions,
          column: :id,
          name: "npc_involvements_quest_version_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :quest_id,
        references(:quests,
          column: :id,
          name: "npc_involvements_quest_id_fkey",
          type: :citext,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    drop_if_exists(
      unique_index(
        :actor_involvements,
        [
          :quest_id,
          :quest_version_id,
          :npc_id,
          :creature_id,
          :reason,
          :dialogue_response_id,
          :dialogue_response_topic_id,
          :script_id
        ], name: "actor_involvements_unique_involvement_index")
    )

    create unique_index(
             :actor_involvements,
             [
               :quest_id,
               :quest_version_id,
               :npc_id,
               :reason,
               :dialogue_response_id,
               :dialogue_response_topic_id,
               :script_id
             ], name: "npc_involvements_unique_involvement_index", nulls_distinct: false)

    alter table(:actor_involvements) do
      remove(:creature_id)
    end

    rename(table(:actor_involvements), to: table(:npc_involvements))
  end
end
