defmodule Resdayn.Repo.Migrations.DropSoundReferencable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:sound_generators, "sound_generators_id_fkey"))

    alter table(:sound_generators) do
      modify(:id, :citext)
    end

    drop(constraint(:sounds, "sounds_id_fkey"))

    alter table(:sounds) do
      modify(:id, :citext)
    end

    # Codegen also emitted `create index` on both `id` columns here, to replace the
    # index the dropped foreign keys provided. Both are removed: `sounds_id_index`
    # already exists from 20250527152018 (untracked by any snapshot, so codegen can't
    # see it) and collides, and either index would only duplicate the tables' primary
    # key indexes. See the id-index cleanup task for the other 16 tables.
  end

  def down do
    drop_if_exists(index(:sounds, [:id]))

    alter table(:sounds) do
      modify(
        :id,
        references(:referencable_objects,
          column: :id,
          name: "sounds_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    drop_if_exists(index(:sound_generators, [:id]))

    alter table(:sound_generators) do
      modify(
        :id,
        references(:referencable_objects,
          column: :id,
          name: "sound_generators_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end
  end
end
