defmodule Resdayn.Repo.Migrations.RecreateQuests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quests, primary_key: false) do
      add(:id, :citext, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:flags, {:array, :text}, null: false, default: [])
      add(:source_file_ids, {:array, :text}, null: false, default: [])

      add(
        :faction_id,
        references(:factions,
          column: :id,
          name: "quests_faction_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    alter table(:quest_versions) do
      remove(:faction_id)

      add(
        :quest_id,
        references(:quests,
          column: :id,
          name: "quest_versions_quest_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:quest_versions, "quest_versions_quest_id_fkey"))

    alter table(:quest_versions) do
      remove(:quest_id)

      add(
        :faction_id,
        references(:factions,
          column: :id,
          name: "quest_versions_faction_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    drop(constraint(:quests, "quests_faction_id_fkey"))

    drop(table(:quests))
  end
end
