defmodule Resdayn.Repo.Migrations.DropTransitionUniqueIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # The `:unique_transition` identity was removed from the Transition
    # resource: two edges from the same source to the same index are distinct
    # when their conditions differ, but only the journal projection
    # (from_min/from_max) is stored, so no column set honestly identifies a
    # transition. The persister rebuilds the table per run instead of upserting.
    drop_if_exists(
      unique_index(
        :transitions,
        [
          :quest_id,
          :quest_version_id,
          :dialogue_response_id,
          :dialogue_response_topic_id,
          :script_id,
          :target_index
        ], name: "transitions_unique_transition_index")
    )

    alter table(:transitions) do
      modify(
        :dialogue_response_topic_id,
        references(:dialogue_topics,
          column: :id,
          name: "transitions_dialogue_response_topic_id_fkey",
          type: :citext,
          prefix: "public"
        )
      )
    end

    create index(:transitions, [:dialogue_response_topic_id])
  end

  def down do
    drop_if_exists(index(:transitions, [:dialogue_response_topic_id]))

    drop(constraint(:transitions, "transitions_dialogue_response_topic_id_fkey"))

    alter table(:transitions) do
      modify(:dialogue_response_topic_id, :citext)
    end

    create unique_index(
             :transitions,
             [
               :quest_id,
               :quest_version_id,
               :dialogue_response_id,
               :dialogue_response_topic_id,
               :script_id,
               :target_index
             ], name: "transitions_unique_transition_index", nulls_distinct: false)
  end
end
