defmodule Resdayn.Repo.Migrations.ConvertIdsToCitext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # All foreign keys that reference columns being converted to citext
  # Format: {table, constraint_name, column, ref_table, ref_column, on_delete}
  # on_delete: :nothing (NO ACTION), :delete_all (CASCADE), :nilify_all (SET NULL)
  @foreign_keys [
    # faction_skills -> factions
    {:faction_skills, :faction_skills_faction_id_fkey, :faction_id, :factions, :id, :nothing},
    # race_skill_bonuses -> races (has CASCADE delete)
    {:race_skill_bonuses, :race_skill_bonuses_race_id_fkey, :race_id, :races, :id, :delete_all},
    # sound_generators -> sounds
    {:sound_generators, :sound_generators_sound_id_fkey, :sound_id, :sounds, :id, :nothing},
    # inventory_items -> referencable_objects (object_ref_id) - has CASCADE delete
    {:inventory_items, :inventory_items_object_ref_id_fkey, :object_ref_id, :referencable_objects, :id, :delete_all},
    # inventory_items -> referencable_objects (holder_ref_id) - has CASCADE delete
    {:inventory_items, :inventory_items_holder_ref_id_fkey, :holder_ref_id, :referencable_objects, :id, :delete_all},
    # cell_references -> global_variables
    {:cell_references, :cell_references_global_variable_id_fkey, :global_variable_id, :global_variables, :id, :nothing},
    # cell_references -> creatures (soul_id)
    {:cell_references, :cell_references_soul_id_fkey, :soul_id, :creatures, :id, :nothing},
    # cell_references -> spells (trap_id)
    {:cell_references, :cell_references_trap_id_fkey, :trap_id, :spells, :id, :nothing},
    # cell_references -> referencable_objects (key_id)
    {:cell_references, :cell_references_key_id_fkey, :key_id, :referencable_objects, :id, :nothing},
    # cell_references -> factions (owner_faction_id)
    {:cell_references, :cell_references_owner_faction_id_fkey, :owner_faction_id, :factions, :id, :nothing},
    # cell_references -> npcs (owner_id)
    {:cell_references, :cell_references_owner_id_fkey, :owner_id, :npcs, :id, :nothing},
    # cell_references -> referencable_objects (reference_id)
    {:cell_references, :cell_references_reference_id_fkey, :reference_id, :referencable_objects, :id, :nothing},
    # cell_references -> cells (has CASCADE delete)
    {:cell_references, :cell_references_cell_id_fkey, :cell_id, :cells, :id, :delete_all},
    # activators -> scripts
    {:activators, :activators_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # journal_entries -> quests
    {:journal_entries, :journal_entries_quest_id_fkey, :quest_id, :quests, :id, :nothing},
    # creatures -> scripts
    {:creatures, :creatures_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # books -> enchantments
    {:books, :books_enchantment_id_fkey, :enchantment_id, :enchantments, :id, :nothing},
    # books -> scripts
    {:books, :books_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # magic_effect_templates -> sounds (hit_sound_id)
    {:magic_effect_templates, :magic_effect_templates_hit_sound_id_fkey, :hit_sound_id, :sounds, :id, :nothing},
    # magic_effect_templates -> sounds (casting_sound_id)
    {:magic_effect_templates, :magic_effect_templates_casting_sound_id_fkey, :casting_sound_id, :sounds, :id, :nothing},
    # magic_effect_templates -> sounds (bolt_sound_id)
    {:magic_effect_templates, :magic_effect_templates_bolt_sound_id_fkey, :bolt_sound_id, :sounds, :id, :nothing},
    # magic_effect_templates -> sounds (area_sound_id)
    {:magic_effect_templates, :magic_effect_templates_area_sound_id_fkey, :area_sound_id, :sounds, :id, :nothing},
    # magic_effect_templates -> game_settings
    {:magic_effect_templates, :magic_effect_templates_game_setting_id_fkey, :game_setting_id, :game_settings, :id, :nothing},
    # miscellaneous_items -> scripts
    {:miscellaneous_items, :miscellaneous_items_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # clothing -> enchantments
    {:clothing, :clothing_enchantment_id_fkey, :enchantment_id, :enchantments, :id, :nothing},
    # clothing -> scripts
    {:clothing, :clothing_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # tools -> scripts
    {:tools, :tools_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # lights -> sounds
    {:lights, :lights_sound_id_fkey, :sound_id, :sounds, :id, :nothing},
    # lights -> scripts
    {:lights, :lights_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # regions -> creatures (disturb_sleep_creature_id)
    {:regions, :regions_disturb_sleep_creature_id_fkey, :disturb_sleep_creature_id, :creature_levelled_lists, :id, :nothing},
    # armor -> enchantments
    {:armor, :armor_enchantment_id_fkey, :enchantment_id, :enchantments, :id, :nothing},
    # armor -> scripts
    {:armor, :armor_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # attributes -> game_settings
    {:attributes, :attributes_description_game_setting_id_fkey, :description_game_setting_id, :game_settings, :id, :nothing},
    # doors -> sounds (close_sound_id)
    {:doors, :doors_close_sound_id_fkey, :close_sound_id, :sounds, :id, :nothing},
    # doors -> sounds (open_sound_id)
    {:doors, :doors_open_sound_id_fkey, :open_sound_id, :sounds, :id, :nothing},
    # doors -> scripts
    {:doors, :doors_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # cells -> regions
    {:cells, :cells_region_id_fkey, :region_id, :regions, :id, :nothing},
    # containers -> scripts
    {:containers, :containers_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # weapons -> enchantments
    {:weapons, :weapons_enchantment_id_fkey, :enchantment_id, :enchantments, :id, :nothing},
    # weapons -> scripts
    {:weapons, :weapons_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # npcs -> factions
    {:npcs, :npcs_faction_id_fkey, :faction_id, :factions, :id, :nothing},
    # npcs -> classes
    {:npcs, :npcs_class_id_fkey, :class_id, :classes, :id, :nothing},
    # npcs -> races
    {:npcs, :npcs_race_id_fkey, :race_id, :races, :id, :nothing},
    # npcs -> scripts
    {:npcs, :npcs_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # faction_reactions -> factions (target_id)
    {:faction_reactions, :faction_reactions_target_id_fkey, :target_id, :factions, :id, :nothing},
    # faction_reactions -> factions (source_id)
    {:faction_reactions, :faction_reactions_source_id_fkey, :source_id, :factions, :id, :nothing},
    # dialogue_responses -> factions (player_faction_id)
    {:dialogue_responses, :dialogue_responses_player_faction_id_fkey, :player_faction_id, :factions, :id, :nothing},
    # dialogue_responses -> factions (speaker_faction_id)
    {:dialogue_responses, :dialogue_responses_speaker_faction_id_fkey, :speaker_faction_id, :factions, :id, :nothing},
    # dialogue_responses -> races
    {:dialogue_responses, :dialogue_responses_speaker_race_id_fkey, :speaker_race_id, :races, :id, :nothing},
    # dialogue_responses -> classes
    {:dialogue_responses, :dialogue_responses_speaker_class_id_fkey, :speaker_class_id, :classes, :id, :nothing},
    # dialogue_responses -> creatures
    {:dialogue_responses, :dialogue_responses_speaker_creature_id_fkey, :speaker_creature_id, :creatures, :id, :nothing},
    # dialogue_responses -> npcs
    {:dialogue_responses, :dialogue_responses_speaker_npc_id_fkey, :speaker_npc_id, :npcs, :id, :nothing},
    # dialogue_responses -> dialogue_topics (has CASCADE delete)
    {:dialogue_responses, :dialogue_responses_topic_id_fkey, :topic_id, :dialogue_topics, :id, :delete_all},
    # ingredient_effects -> magic_effects
    {:ingredient_effects, :ingredient_effects_magic_effect_id_fkey, :magic_effect_id, :magic_effects, :id, :nothing},
    # ingredient_effects -> ingredients
    {:ingredient_effects, :ingredient_effects_ingredient_id_fkey, :ingredient_id, :ingredients, :id, :nothing},
    # alchemy_apparatus -> scripts
    {:alchemy_apparatus, :alchemy_apparatus_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # npc_skill_values -> npcs
    {:npc_skill_values, :npc_skill_values_npc_id_fkey, :npc_id, :npcs, :id, :nothing},
    # class_skills -> classes
    {:class_skills, :class_skills_class_id_fkey, :class_id, :classes, :id, :nothing},
    # body_parts -> races
    {:body_parts, :body_parts_race_id_fkey, :race_id, :races, :id, :nothing},
    # ingredients -> scripts
    {:ingredients, :ingredients_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # potions -> scripts
    {:potions, :potions_script_id_fkey, :script_id, :scripts, :id, :nothing},
    # applied_magic_effects -> magic_effects
    {:applied_magic_effects, :applied_magic_effects_magic_effect_id_fkey, :magic_effect_id, :magic_effects, :id, :nothing},

    # ============================================
    # Referencable extension: id -> referencable_objects.id
    # These are added by the Resdayn.Codex.Referencable extension
    # All use NO ACTION (default)
    # ============================================
    # Assets
    {:lights, :lights_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:sounds, :sounds_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:sound_generators, :sound_generators_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:static_objects, :static_objects_id_fkey, :id, :referencable_objects, :id, :nothing},
    # Items
    {:alchemy_apparatus, :alchemy_apparatus_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:armor, :armor_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:books, :books_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:clothing, :clothing_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:ingredients, :ingredients_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:item_levelled_lists, :item_levelled_lists_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:miscellaneous_items, :miscellaneous_items_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:potions, :potions_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:tools, :tools_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:weapons, :weapons_id_fkey, :id, :referencable_objects, :id, :nothing},
    # World
    {:activators, :activators_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:containers, :containers_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:creatures, :creatures_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:creature_levelled_lists, :creature_levelled_lists_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:doors, :doors_id_fkey, :id, :referencable_objects, :id, :nothing},
    {:npcs, :npcs_id_fkey, :id, :referencable_objects, :id, :nothing}
  ]

  defp drop_foreign_keys do
    Enum.each(@foreign_keys, fn {table, constraint_name, _column, _ref_table, _ref_column, _on_delete} ->
      execute "ALTER TABLE #{table} DROP CONSTRAINT IF EXISTS #{constraint_name}"
    end)
  end

  defp add_foreign_keys do
    Enum.each(@foreign_keys, fn {table, constraint_name, column, ref_table, ref_column, on_delete} ->
      on_delete_clause =
        case on_delete do
          :delete_all -> "ON DELETE CASCADE"
          :nilify_all -> "ON DELETE SET NULL"
          :nothing -> "ON DELETE NO ACTION"
        end

      execute """
      ALTER TABLE #{table}
      ADD CONSTRAINT #{constraint_name}
      FOREIGN KEY (#{column}) REFERENCES #{ref_table}(#{ref_column})
      #{on_delete_clause}
      """
    end)
  end

  def up do
    # Drop all foreign keys first
    drop_foreign_keys()

    alter table(:spells) do
      modify(:id, :citext)
    end

    alter table(:faction_skills) do
      modify(:faction_id, :citext)
    end

    alter table(:race_skill_bonuses) do
      modify(:race_id, :citext)
    end

    alter table(:creature_levelled_lists) do
      modify(:id, :citext)
    end

    alter table(:sound_generators) do
      modify(:sound_id, :citext)
      modify(:id, :citext)
    end

    alter table(:races) do
      modify(:id, :citext)
    end

    alter table(:inventory_items) do
      modify(:object_ref_id, :citext)
      modify(:holder_ref_id, :citext)
    end

    alter table(:cell_references) do
      modify(:global_variable_id, :citext)
      modify(:soul_id, :citext)
      modify(:trap_id, :citext)
      modify(:key_id, :citext)
      modify(:owner_faction_id, :citext)
      modify(:owner_id, :citext)
      modify(:reference_id, :citext)
      modify(:cell_id, :citext)
    end

    alter table(:activators) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:scripts) do
      modify(:id, :citext)
    end

    alter table(:journal_entries) do
      modify(:quest_id, :citext)
      modify(:id, :citext)
    end

    alter table(:creatures) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:books) do
      modify(:enchantment_id, :citext)
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:referencable_objects) do
      modify(:id, :citext)
    end

    alter table(:search_index) do
      modify(:id, :citext)
    end

    alter table(:static_objects) do
      modify(:id, :citext)
    end

    alter table(:magic_effect_templates) do
      modify(:hit_sound_id, :citext)
      modify(:casting_sound_id, :citext)
      modify(:bolt_sound_id, :citext)
      modify(:area_sound_id, :citext)
      modify(:game_setting_id, :citext)
    end

    alter table(:miscellaneous_items) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:birthsigns) do
      modify(:id, :citext)
    end

    alter table(:global_variables) do
      modify(:id, :citext)
    end

    alter table(:game_settings) do
      modify(:id, :citext)
    end

    alter table(:clothing) do
      modify(:enchantment_id, :citext)
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:tools) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:lights) do
      modify(:sound_id, :citext)
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:regions) do
      modify(:disturb_sleep_creature_id, :citext)
      modify(:id, :citext)
    end

    alter table(:armor) do
      modify(:enchantment_id, :citext)
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:attributes) do
      modify(:description_game_setting_id, :citext)
    end

    alter table(:quests) do
      modify(:id, :citext)
    end

    alter table(:doors) do
      modify(:close_sound_id, :citext)
      modify(:open_sound_id, :citext)
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:data_files) do
      modify(:id, :citext)
    end

    alter table(:cells) do
      modify(:region_id, :citext)
      modify(:id, :citext)
    end

    alter table(:containers) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:weapons) do
      modify(:enchantment_id, :citext)
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:dialogue_topics) do
      modify(:id, :citext)
    end

    alter table(:magic_effects) do
      modify(:id, :citext)
    end

    alter table(:npcs) do
      modify(:faction_id, :citext)
      modify(:class_id, :citext)
      modify(:race_id, :citext)
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:faction_reactions) do
      modify(:target_id, :citext)
      modify(:source_id, :citext)
    end

    alter table(:dialogue_responses) do
      modify(:player_faction_id, :citext)
      modify(:speaker_faction_id, :citext)
      modify(:speaker_race_id, :citext)
      modify(:speaker_class_id, :citext)
      modify(:speaker_creature_id, :citext)
      modify(:speaker_npc_id, :citext)
      modify(:topic_id, :citext)
      modify(:next_response_id, :citext)
      modify(:previous_response_id, :citext)
      modify(:id, :citext)
    end

    alter table(:ingredient_effects) do
      modify(:magic_effect_id, :citext)
      modify(:ingredient_id, :citext)
    end

    alter table(:item_levelled_lists) do
      modify(:id, :citext)
    end

    alter table(:alchemy_apparatus) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:npc_skill_values) do
      modify(:npc_id, :citext)
    end

    alter table(:class_skills) do
      modify(:class_id, :citext)
    end

    alter table(:classes) do
      modify(:id, :citext)
    end

    alter table(:sounds) do
      modify(:id, :citext)
    end

    alter table(:body_parts) do
      modify(:race_id, :citext)
      modify(:id, :citext)
    end

    alter table(:ingredients) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:factions) do
      modify(:id, :citext)
    end

    alter table(:enchantments) do
      modify(:id, :citext)
    end

    alter table(:potions) do
      modify(:script_id, :citext)
      modify(:id, :citext)
    end

    alter table(:applied_magic_effects) do
      modify(:magic_effect_id, :citext)
      modify(:parent_id, :citext)
    end

    # Re-add all foreign keys
    add_foreign_keys()
  end

  def down do
    # Drop all foreign keys first
    drop_foreign_keys()

    alter table(:applied_magic_effects) do
      modify(:parent_id, :text)
      modify(:magic_effect_id, :text)
    end

    alter table(:potions) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:enchantments) do
      modify(:id, :text)
    end

    alter table(:factions) do
      modify(:id, :text)
    end

    alter table(:ingredients) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:body_parts) do
      modify(:id, :text)
      modify(:race_id, :text)
    end

    alter table(:sounds) do
      modify(:id, :text)
    end

    alter table(:classes) do
      modify(:id, :text)
    end

    alter table(:class_skills) do
      modify(:class_id, :text)
    end

    alter table(:npc_skill_values) do
      modify(:npc_id, :text)
    end

    alter table(:alchemy_apparatus) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:item_levelled_lists) do
      modify(:id, :text)
    end

    alter table(:ingredient_effects) do
      modify(:ingredient_id, :text)
      modify(:magic_effect_id, :text)
    end

    alter table(:dialogue_responses) do
      modify(:id, :text)
      modify(:previous_response_id, :text)
      modify(:next_response_id, :text)
      modify(:topic_id, :text)
      modify(:speaker_npc_id, :text)
      modify(:speaker_creature_id, :text)
      modify(:speaker_class_id, :text)
      modify(:speaker_race_id, :text)
      modify(:speaker_faction_id, :text)
      modify(:player_faction_id, :text)
    end

    alter table(:faction_reactions) do
      modify(:source_id, :text)
      modify(:target_id, :text)
    end

    alter table(:npcs) do
      modify(:id, :text)
      modify(:script_id, :text)
      modify(:race_id, :text)
      modify(:class_id, :text)
      modify(:faction_id, :text)
    end

    alter table(:magic_effects) do
      modify(:id, :text)
    end

    alter table(:dialogue_topics) do
      modify(:id, :text)
    end

    alter table(:weapons) do
      modify(:id, :text)
      modify(:script_id, :text)
      modify(:enchantment_id, :text)
    end

    alter table(:containers) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:cells) do
      modify(:id, :text)
      modify(:region_id, :text)
    end

    alter table(:data_files) do
      modify(:id, :text)
    end

    alter table(:doors) do
      modify(:id, :text)
      modify(:script_id, :text)
      modify(:open_sound_id, :text)
      modify(:close_sound_id, :text)
    end

    alter table(:quests) do
      modify(:id, :text)
    end

    alter table(:attributes) do
      modify(:description_game_setting_id, :text)
    end

    alter table(:armor) do
      modify(:id, :text)
      modify(:script_id, :text)
      modify(:enchantment_id, :text)
    end

    alter table(:regions) do
      modify(:id, :text)
      modify(:disturb_sleep_creature_id, :text)
    end

    alter table(:lights) do
      modify(:id, :text)
      modify(:script_id, :text)
      modify(:sound_id, :text)
    end

    alter table(:tools) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:clothing) do
      modify(:id, :text)
      modify(:script_id, :text)
      modify(:enchantment_id, :text)
    end

    alter table(:game_settings) do
      modify(:id, :text)
    end

    alter table(:global_variables) do
      modify(:id, :text)
    end

    alter table(:birthsigns) do
      modify(:id, :text)
    end

    alter table(:miscellaneous_items) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:magic_effect_templates) do
      modify(:game_setting_id, :text)
      modify(:area_sound_id, :text)
      modify(:bolt_sound_id, :text)
      modify(:casting_sound_id, :text)
      modify(:hit_sound_id, :text)
    end

    alter table(:static_objects) do
      modify(:id, :text)
    end

    alter table(:search_index) do
      modify(:id, :text)
    end

    alter table(:referencable_objects) do
      modify(:id, :text)
    end

    alter table(:books) do
      modify(:id, :text)
      modify(:script_id, :text)
      modify(:enchantment_id, :text)
    end

    alter table(:creatures) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:journal_entries) do
      modify(:id, :text)
      modify(:quest_id, :text)
    end

    alter table(:scripts) do
      modify(:id, :text)
    end

    alter table(:activators) do
      modify(:id, :text)
      modify(:script_id, :text)
    end

    alter table(:cell_references) do
      modify(:cell_id, :text)
      modify(:reference_id, :text)
      modify(:owner_id, :text)
      modify(:owner_faction_id, :text)
      modify(:key_id, :text)
      modify(:trap_id, :text)
      modify(:soul_id, :text)
      modify(:global_variable_id, :text)
    end

    alter table(:inventory_items) do
      modify(:holder_ref_id, :text)
      modify(:object_ref_id, :text)
    end

    alter table(:races) do
      modify(:id, :text)
    end

    alter table(:sound_generators) do
      modify(:id, :text)
      modify(:sound_id, :text)
    end

    alter table(:creature_levelled_lists) do
      modify(:id, :text)
    end

    alter table(:race_skill_bonuses) do
      modify(:race_id, :text)
    end

    alter table(:faction_skills) do
      modify(:faction_id, :text)
    end

    alter table(:spells) do
      modify(:id, :text)
    end

    # Re-add all foreign keys
    add_foreign_keys()
  end
end
