defmodule Resdayn.Codex.Characters.BodyPart.CoverableType do
  use Ash.Type.Enum,
    values: [
      head: [label: "Head"],
      hair: [label: "Hair"],
      neck: [label: "Neck"],
      cuirass: [label: "Cuirass"],
      groin: [label: "Groin"],
      skirt: [label: "Skirt"],
      right_hand: [label: "Right Hand"],
      left_hand: [label: "Left Hand"],
      right_wrist: [label: "Right Wrist"],
      left_wrist: [label: "Left Wrist"],
      shield: [label: "Shield"],
      right_forearm: [label: "Right Forearm"],
      left_forearm: [label: "Left Forearm"],
      right_upper_arm: [label: "Right Upper Arm"],
      left_upper_arm: [label: "Left Upper Arm"],
      right_foot: [label: "Right Foot"],
      left_foot: [label: "Left Foot"],
      right_ankle: [label: "Right Ankle"],
      left_ankle: [label: "Left Ankle"],
      right_knee: [label: "Right Knee"],
      left_knee: [label: "Left Knee"],
      right_upper_leg: [label: "Right Upper Leg"],
      left_upper_leg: [label: "Left Upper Leg"],
      right_pauldron: [label: "Right Pauldron"],
      left_pauldron: [label: "Left Pauldron"],
      weapon: [label: "Weapon"],
      tail: [label: "Tail"]
    ]
end
