defmodule Resdayn.Codex.Characters.BodyPart.CoverableType do
  use Ash.Type.Enum,
    values: [
      head: "Head",
      hair: "Hair",
      neck: "Neck",
      cuirass: "Cuirass",
      groin: "Groin",
      skirt: "Skirt",
      right_hand: "Right Hand",
      left_hand: "Left Hand",
      right_wrist: "Right Wrist",
      left_wrist: "Left Wrist",
      shield: "Shield",
      right_forearm: "Right Forearm",
      left_forearm: "Left Forearm",
      right_upper_arm: "Right Upper Arm",
      left_upper_arm: "Left Upper Arm",
      right_foot: "Right Foot",
      left_foot: "Left Foot",
      right_ankle: "Right Ankle",
      left_ankle: "Left Ankle",
      right_knee: "Right Knee",
      left_knee: "Left Knee",
      right_upper_leg: "Right Upper Leg",
      left_upper_leg: "Left Upper Leg",
      right_pauldron: "Right Pauldron",
      left_pauldron: "Left Pauldron",
      weapon: "Weapon",
      tail: "Tail"
    ]
end
